import react from '@fractionax/config/eslint/react';

export default [
  ...react,
  {
    // next-env.d.ts is generated by `next build` and contains a triple-slash
    // reference that conflicts with @typescript-eslint rules.
    ignores: ['next-env.d.ts', '.next/**'],
  },
];
